### ISSUE TITLE
Some issues about Your Paper LSMGA

### ISSUE THREAD

**Issue by HLiang-Lee** [RongchuanTang/LSMGA-MKGC#1]
Dear Tang:
    Hi! I'm Hongliang Li from BJTUNLP.
    We have read your paper "Multilingual Knowledge Graph Completion with Language-Sensitive Multi-Graph Attention" and we are interested in your proposed LSMGA. We have run the open-source code with the datasets (i.e., DBP-5L, EPKG) provided by your paper under the default parameters. However, the results are inconsistent with that reported in your paper. Thus, we wonder the reason for such inconsistent results.
    The results on DBP-5L and EPKG reported in your paper:
<img width="490" alt="image" src="https://github.com/RongchuanTang/LSMGA-MKGC/assets/79565908/f50fb764-fe21-4d75-a1c2-592d34e55a0f">
    The results on DBP-5L and EPKG  obtained by rurning your code from ( [github LSMGA-MKGC](https://github.com/RongchuanTang/LSMGA-MKGC) )
<img width="489" alt="image" src="https://github.com/RongchuanTang/LSMGA-MKGC/assets/79565908/3824017c-30d3-414d-9943-c85f4183ca6a">
    As shown in the above table, the actual results are seriously inconsistent with the original paper (e.g., FR in the DBP-5L;  DE, EN and JA in EPKG). The result with a large gap is marked in red for emphasis.
    We provide you with the training logs on DBP-5L and EPKG. Regarding experimental environment, we use the Pytorch 1.7.1 (python3.6.8, cuda 10.1, cudnn7.6, torchvision0.8.2) framework to run the model. All computations are done on a P40 GPU. We directly adopt the hyper-parameters in the open-source code, which can be seen in the training logs.
    We do hope you can provide us with some relevant details to explain our doubts. Thanks.​

Best,
Hongliang Li

**Comment by RongchuanTang** [comment]
你好，这个应该是随机初始化的问题，可以更改随机种子多跑几次看看

**Comment by HLiang-Lee** [comment]
方便知道您跑论文结果的时候，用的是多少的随机种子嘛？顺便问一句，您当时复现SS-AGA那个了嘛？效果怎么样。

**Comment by RongchuanTang** [comment]
实验主要用的3407，后面随机跑了几次，差别也不是太大。SS-AGA的结果我复现的时候，Hits@1的结果没有跑到论文里的数据，不过也没跑几遍

**Comment by RongchuanTang** [comment]
你发给我的log文件里似乎没有filter之后的数据，应该是要经过filter操作的
