### ISSUE TITLE
复现结果仍存在一定误差，这是否在可以接受的范围内？

### ISSUE THREAD

**Issue by HLiang-Lee** [RongchuanTang/LSMGA-MKGC#2]
您好！非常感谢您之前的指导，在新的训练结果中，实验结果（filtered）已经几乎接近于论文结果，但部分指标还是相差1%左右，请问您当时实验时，指标的浮动大概范围是什么呢？相差1%是不是在可以接受的范围内。

以下是复现结果与原文的对比：
![image](https://github.com/RongchuanTang/LSMGA-MKGC/assets/79565908/67285481-7fdf-442c-8710-fc1689fdc297)

上述图片中的实验结果的log文件，已经发您邮箱。

**Comment by RongchuanTang** [comment]
DBP-5L数据集需要训练更多的轮次，已在指令里添加建议的round参数

**Comment by HLiang-Lee** [comment]
好的，已经看到啦！谢谢您

**Comment by HLiang-Lee** [comment]
哦对了，在设置随机数时，需要为numpy也设置同torch一样的随机数嘛？还是您仅设置了torch的随机数呀？

**Comment by RongchuanTang** [comment]
random和torch就行，numpy没有用于计算
